### ISSUE TITLE
I wonder if this repo is the simulator code for GPUShield in ISCA 2022

### ISSUE THREAD

**Issue by NeilAlfred** [cwang360/vortex-gpushield#1]
I have read paper "Securing GPU via Region-based Bounds Checking" in ISCA 2022 and I am interested in it, but there seems to be no public repo of its source code on github? Then I found this repo, which has keywords like "GPUshield" and "bound-checking" in its description.

So I have a question here, I wonder if this repo stores the simulator code for GPUShield in ISCA 2022? If it is, I would consider myself so lucky :)

**Comment by cwang360** [comment]
Hi, unfortunately this is not the simulator code for the original GPUShield paper. This repo contains simulator code for the GPUShield protection scheme implemented on the open-source Vortex GPGPU (basically, just a modified version of SimX from [here](https://github.com/vortexgpgpu/vortex)), for a course project. You may want to contact the authors of the paper regarding the MacSim simulator they used for evaluating GPUShield on Nvidia and Intel GPU architectures. MacSim is open-source [here](https://github.com/gthparch/macsim), but I'm not sure if it contains the version with GPUShield if you're looking for that.

**Comment by NeilAlfred** [comment]
Thank you bro, I will try to contact the authors👍
